name: Lint, Prettier, Test

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main  

jobs:
  # Job for Linting
  
        
  Adrix-Llou-Dagsa:
    runs-on: ubuntu-latest
    steps:
      - name: Display Name
        run: echo "Adrix Llou Dagsa"

      - name: List current directory
        run: ls -R 

      - name: Create ZIP file
        run: |
          zip -r build-artifact.zip ./dist

      - name: Upload ZIP artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: build-artifact.zip
